### ISSUE TITLE
Android gradle plugin minimum now 0.7

### ISSUE THREAD

**Issue by stonier** [rosjava/rosjava_bootstrap#15]

**Comment by dwlee** [comment]
I used the gradle plugin version 0.7.0. But the error occurs.
How do we use minimum 0.7.1?
http://stackoverflow.com/questions/20673625/android-gradle-plugin-0-7-0-duplicate-files-during-packaging-of-apk

**Comment by stonier** [comment]
Some discussion and workarounds for the packaging problem in https://github.com/rosjava/android_core/issues/200.
