### ISSUE TITLE
After publishing my Android app on Google Play I've got "Supported devices 0" warning

### ISSUE THREAD

**Issue by DmitryDzz** [rosjava/rosjava_bootstrap#37]
In the app's details in Google Play developer console there was a message: "Native platforms: commons-codec-1.8.jar, commons-io-2.4.jar, commons-lang-2.6.jar".

**Comment by talregev** [comment]
you can't publish your app?

**Comment by talregev** [comment]
codec-1.8.jar, commons-io-2.4.jar and commons-lang-2.6.jar are dependents on the libraries your wrote, and not for spring library.

**Comment by DmitryDzz** [comment]
Oh, seems like I didn't close the issue...
I could publish my app. But it was visible for 0 devices :)
I think I've [solved](https://github.com/rosjava/rosjava_bootstrap/pull/38) this issue. And I've published the app after this fix. Now it is visible for most of devices on Google Play market.

**Comment by talregev** [comment]
How i can see for how many devices is visible?

**Comment by talregev** [comment]
I Publish my app without your fix, and I can install on all my devices.
Is there other way to see which support devices for my app?

**Comment by DmitryDzz** [comment]
I saw that in my Google Play Developer Console. Take a look at "APK" tab. There's "Supported devices" field. Before I fixed the issue it was zero but at the same time I could install the apk on all my devices using adb. I couldn't do that from Market. The fix solved Market installation.

**Comment by talregev** [comment]
if you do this fix, how you solve the duplicate multi-dex on android_core? 
Your fix maybe fit to your app, but it get a lot of work to ROS, and other ros app that compile with android_core, don't need that fix and can freely publish and support many devices.

**Comment by talregev** [comment]
Thanks for the tip, I can see my app supported a 7266 devices.

**Comment by DmitryDzz** [comment]
Well... that's strange. I could build android_core after the fix. May be something changed since that time... It's great that your app is supported by other devices without this fix. Ok, can you rollback the changes? I'm afraid I'm too far from the project right now.

**Comment by talregev** [comment]
we already rollback your change. you can look on the commits.

**Comment by talregev** [comment]
sorry for time consume :)

**Comment by DmitryDzz** [comment]
Oh, that's great. Thanks! :)
