### ISSUE TITLE
FYI: gradle 2.3 released

### ISSUE THREAD

**Issue by vrabaud** [rosjava/rosjava_bootstrap#42]
https://services.gradle.org/distributions/

It's just FYI, no idea on whether you guys keep track of that closely

**Comment by stonier** [comment]
Usually we update whenever android studio forces us...i.e. it often sets a minimum dependency requirement. This applies to the android stacks only of course, but it's good to have the rosjava stacks in sync.

**Comment by stonier** [comment]
I just swept through the rosjava stacks and updated them to 2.2.1 last week. Will update to 2.3 if android studio needs it (just freshly downloaded).

**Comment by jubeira** [comment]
Using Gradle 4.10 now.
