### ISSUE TITLE
No default maven repository set in the plugin

### ISSUE THREAD

**Issue by stonier** [rosjava/rosjava_bootstrap#46]
Looks like we have a bug in the [ros plugin](https://github.com/rosjava/rosjava_bootstrap/blob/indigo/gradle_plugins/src/main/groovy/org/ros/gradle_plugins/RosPlugin.groovy).

When there aren't any environment variables (windows), the system getenv calls return null, wiping out the defaults that were set in the extension [constructor](https://github.com/rosjava/rosjava_bootstrap/blob/indigo/gradle_plugins/src/main/groovy/org/ros/gradle_plugins/RosPlugin.groovy#L62).

Should also think about what is a good default for the `ROS_MAVEN_DEPLOYMENT_REPOSITORY` on windows.

**Comment by stonier** [comment]
@talregev reopen this one if windows continues to be a problem.

**Comment by talregev** [comment]
can you add a minor version for bootstrap, compile, and upload to maven_repo?
it will make the check more easy. :)

**Comment by stonier** [comment]
[rosjava_bootstrap 0.2.1](https://github.com/rosjava/rosjava_mvn_repo/tree/master/org/ros/rosjava_bootstrap/gradle_plugins/0.2.1) is in the maven repo.

**Comment by talregev** [comment]
thanks! :+1:
