### ISSUE TITLE
Outdated buildToolsVersion in ros-android gradle plugin

### ISSUE THREAD

**Issue by wmmc88** [rosjava/rosjava_bootstrap#79]
When applying the ros-android gradle plugin, I get the following warning from Android Studio:

`WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Remove Build Tools version and sync project`

project level build.gradle
```
buildscript {
    apply from: "https://github.com/rosjava/android_core/raw/kinetic/buildscript.gradle"
}

allprojects {
    repositories {
        google()
        jcenter()

    }
}

subprojects {

    apply plugin: 'ros-android'

    afterEvaluate { project ->
        android {
            // Exclude a few files that are duplicated across our dependencies and
            // prevent packaging Android applications.
            packagingOptions {
                exclude "META-INF/LICENSE.txt"
                exclude "META-INF/NOTICE.txt"
            }
            lintOptions {
                abortOnError false
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by wmmc88** [comment]
Is it because https://github.com/rosjava/rosjava_bootstrap/blob/kinetic/buildscript.gradle#L42 is a dead link?

**Comment by jubeira** [comment]
Hi @wmmc88, thanks for the observation.

That part was actually fixed here: https://github.com/rosjava/rosjava_bootstrap/pull/73, but I think the problem is that the Maven repository has not been updated yet (see https://github.com/rosjava/rosjava_mvn_repo/issues/63).

I'll update Maven repo with the latest `rosjava_bootstrap`.

**Comment by wmmc88** [comment]
resolved by https://github.com/rosjava/rosjava_mvn_repo/pull/64

**Comment by wmmc88** [comment]
@jubeira not sure if related but after the pr, I could no longer convert the rostime to seconds anymore and cant find the time class' javadoc. https://answers.ros.org/question/313059/rosjava-get-current-time/

**Comment by jubeira** [comment]
@wmmc88 could you solve your problem with the time conversion? I can't see your question anymore.

**Comment by wmmc88** [comment]
Ye I'm not sure what it was, maybe my caches didn't update correctly or Smth but I got it fixed
